### ISSUE TITLE
Switch tabs doesn't work on and to non pinned tab

### ISSUE THREAD

**Issue by ambrt** [benji300/joplin-note-tabs#10]
tabsSwitchRight doesn't go to last active non-pinned tab.

Same, while being in last non pinned tab command tabsSwitchLeft doesn't work.

joplin v.1.5.7

**Comment by benji300** [comment]
Its a limitation in the current implementation. I've already planned to change this and so the behavior will be changed in the upcoming release.

**Comment by ambrt** [comment]
> Its a limitation in the current implementation. I've already planned to change this and so the behavior will be changed in the upcoming release.
Good to know, closing this then.
