### ISSUE TITLE
Make tabs auto pin when edited

### ISSUE THREAD

**Issue by Awbmilne** [benji300/joplin-note-tabs#11]
I use VScode a lot, and it has a great feature that could make editing and browsing notes easy without the hassle of manually pinning and unpinning tabs.

When you open a file in vscode, the title in the tab shows up as italic. This indicates that the file is _termprarily_ open. If you open another file without editing the temporary one, it closes and the tab is removed. BUT, if you _edit_ the temporary file, The title becomes non-italic and the tab is open. You then need to close the tab with the `x` or use `ctrl+w` to close it.

Here is an example:

![VScode Tabs](https://user-images.githubusercontent.com/50780746/101995006-b9810980-3c94-11eb-975a-d065bf288844.gif)

Notice:
- A tab stops being temporary when the file in the list is double-clicked (whether already open or not)
- A tab stops being temporary when the tab is double clicked
- A tab stops being temporary when the file is edited

It may be hard to tell the difference between a temporary and non-temporary tab in that Gif, here is a better shot of just the italics changing:

![VScode Tabs (Zoom)](https://user-images.githubusercontent.com/50780746/101995060-390ed880-3c95-11eb-8dbf-995898b3bb36.gif)

You can also close any tab easily using the `x`, or the Current tab with `Ctrl+W`

![VScode Tabs (Close)](https://user-images.githubusercontent.com/50780746/101995130-dff37480-3c95-11eb-9c9e-2d6d8e976439.gif)

These are very developer oriented functions, allowing you to read through a file without adding to your numerous tabs already open. **But** i find it would help me greatly with managing multiple open notes at the same time. 

Though, it may be a nucence for some who would use tabs rarely. So a option to toggle this functionality may be required.

**Comment by benji300** [comment]
Addition:
For "**A tab stops being temporary when the file is edited**", I would add an option like: `Automatically pin edited notes`
