### ISSUE TITLE
Retain Position Within Tab when Switching Between Tabs

### ISSUE THREAD

**Issue by dfwdraco76** [benji300/joplin-note-tabs#19]
I need to switch from one tab to another to reference information, but when I switch back, it's lost my place.  I then have to find my place again, often losing my train of thought in the process.   Is it possible to retain that location somehow?

**Comment by benji300** [comment]
I'm not quite sure if it is possible at the moment. I will check it...

**Comment by SugoiDev** [comment]
If the markdown editor is visible, it seems to remember the position when the note markup is HTML, but not when it is Markdown.
It also remembers the position if you're viewing the note both in the html preview and in the rich text editor.


Tested on Joplin 1.6.6 on Windows.

**Comment by dfwdraco76** [comment]
I do use the markdown editor.
Linux Mint 20.1
Joplin 1.5.14 (prod, linux)

**Comment by benji300** [comment]
It is already planned as a core feature of the App. See [here](https://github.com/laurent22/joplin/issues/520) and in the [forum](https://discourse.joplinapp.org/t/save-cursor-position-within-the-note/43/6). I think you should ask for this feature there.
