### ISSUE TITLE
error

### ISSUE THREAD

**Issue by johe123qwe** [benji300/joplin-note-tabs#20]
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Cannot read property 'indexOf' of undefined

Version info
Joplin for Desktop

Copyright © 2016-2021 Laurent Cozic
Joplin 1.6.6 (prod, darwin)

客户端 ID: ea89f3c534a141028d3c0ad6cdfb0009
同步版本: 2
配置文件版本: 34
支持的密钥链: 是

修订: f58b756 (master)

**Comment by benji300** [comment]
Could you please provide some more information? Is it possible to reproduce? 
What were the steps to raise this error? Which command was triggered?
How many tabs were opened/pinned?
