### ISSUE TITLE
Plugin not showing when using "search for plugins"

### ISSUE THREAD

**Issue by SugoiDev** [benji300/joplin-note-tabs#23]
Joplin 1.6.6 on Windows isn't showing the plugin:

![image](https://user-images.githubusercontent.com/7355630/104218929-33371f00-541c-11eb-973a-04e4c10df8e5.png)

I've been using it directly from this repo so I never noticed it wasn't showing in the search results.
I removed the `jpl` to check and it is still not being found.

**Comment by benji300** [comment]
That's because I haven't published it yet to the plugin repository. As soon as that happens, I will post it in the [forum](https://discourse.joplinapp.org/t/plugin-note-tabs/12752).
