### ISSUE TITLE
Add option to select unpin behavior

### ISSUE THREAD

**Issue by benji300** [benji300/joplin-note-tabs#25]
Add user option to specify the behavior when the selected note is unpinned from the tabs.
Selectable values:

- `KEEP_SELECTED` - current behavior, selected note is unpinned and replaces temporary tab
- `SELECT_LAST_ACTIVE` - selected note is completely removed from tabs and the last edited note is selected
- `SELECT_ADJACENT` - same behavior for current selected note  as `SELECT_LAST_ACTIVE`, but new selected note will be either the left or right adjacent note. Depending on which exists. Where the left one is preferred.

**Comment by benji300** [comment]
Waiting for this [discussion](https://discourse.joplinapp.org/t/how-to-create-dropdown-in-plugin-settings/13867).

**Comment by pianoboysai** [comment]
can we have a option to do like this,  when I click a note not in the tabs, it can create a new tab and show it (like chrome)... 

currently it always replaces the last unpinned one.

**Comment by benji300** [comment]
@pianoboysai: I'm not quite sure if I understood you correctly. Do you know the command `Tabs: Pin note`? This is used to pin a note directly to the tabs. It can be called from the context menu for any note (must not be the selected one). However, it does not automatically select (open) the note. 
Is this what you mean? When selecting a note, pin it directly and not open it as a temporary tab?

**Comment by pianoboysai** [comment]
> @pianoboysai: I'm not quite sure if I understood you correctly. Do you know the command `Tabs: Pin note`? This is used to pin a note directly to the tabs. It can be called from the context menu for any note (must not be the selected one). However, it does not automatically select (open) the note.
> Is this what you mean? When selecting a note, pin it directly and not open it as a temporary tab?

Hi benji300, what I mean is, when I select a note in sidebar, directly open it in a new tab （just like chrome）, do not replace content in current pined tab.

**Comment by benji300** [comment]
I've created a new ticket #35 for this.
