### ISSUE TITLE
Add ability to scroll tab bar left and right with scroll wheel without holding shift

### ISSUE THREAD

**Issue by snow1776** [benji300/joplin-note-tabs#34]
This is the standard behaviour of my browser. You mentioned it might not be possible. If you are sure it's not, then please delete this.

**Comment by benji300** [comment]
In fact, I may have found a solution on the Internet how to change the behavior after all. I would definitely like to have a look at it, since it interests me myself. But do not know yet when I will get to it.

**Comment by snow1776** [comment]
> 
> 
> In fact, I may have found a solution on the Internet how to change the behavior after all. I would definitely like to have a look at it, since it interests me myself. But do not know yet when I will get to it.

I'm not sure about github-etiquette, but I wanted to express my appreciation for your work on the plugin. Thanks!
