### ISSUE TITLE
Broken UI for note tabs

### ISSUE THREAD

**Issue by subinvarghesein** [benji300/joplin-note-tabs#38]
**Details:**
System:
MacBook Pro (15-inch, 2017)
MacOS Catalina v10.15.7

Joplin:
Joplin 1.7.11 (prod, darwin)
Revision: f560563 (master)

Note Tabs:
<img width="300" alt="Screen Shot 2021-02-12 at 11 21 10 AM" src="https://user-images.githubusercontent.com/120764/107734947-96221b80-6d24-11eb-8faf-3dd768c51b27.png">

-----

**Issue:**

Tabs are not coming right above the Notes
<img width="1679" alt="Screen Shot 2021-02-12 at 11 20 44 AM" src="https://user-images.githubusercontent.com/120764/107734939-93272b00-6d24-11eb-91d0-b027bc2accb5.png">

**How to fix this?**

Tried: 
1. disabling-enabling the plugin
2. uninstalling-installing the plugin

**Comment by benji300** [comment]
Currently you have to move the panel to your desired position manually. How to do this see here: https://github.com/benji300/joplin-note-tabs#place-the-panel
