### ISSUE TITLE
Tabs become unresponsive

### ISSUE THREAD

**Issue by heviiguy** [benji300/joplin-note-tabs#39]
My instance of this plug-in just froze again. I had to quit and restart to regain functionality

I had only had Joplin open for an hour or so when the tabs became completely unresponsive. Everything else, including the favourites tab as well as being able to navigate to notebooks and notes worked as expected.

Prior to crashing, I was cutting and pasting md table code from 50 or so individual notes in order to consolidate the individual table into one note. I hadn't been making use of the Note Tabs feature during this time.

Joplin 1.7.11 on Mac OS 11
Note Tabs v 1.2.0

**Comment by benji300** [comment]
Hello @heviiguy,
the latest release [v1.2.1](https://github.com/benji300/joplin-note-tabs/releases/tag/v1.2.1) fixed issue #36, could you please check if this also fixes your issue?
Thanks.

**Comment by heviiguy** [comment]
>  could you please check if this also fixes your issue?

If you're referring to the numerous instances of "Joplin Helper (Renderer)" running simultaneously, no it hasn't fixed that issue. 

Since I just now updated the plugin, I'll let you know if the tabs freeze again.

**Comment by benji300** [comment]
> If you're referring to the numerous instances of "Joplin Helper (Renderer)" running simultaneously, no it hasn't fixed that issue.

This is not a problem at all. I guess the number of processes depends on the number of active plugins and other factors. I think it comes from the basic architecture of Electron. See Chrome which creates an own process for each opened tab.

Anyway, it is not something that is caused exclusively by this plugin. If it is, however, I don't know how to prevent it.
