### ISSUE TITLE
Add commands for switching tabs

### ISSUE THREAD

**Issue by danil-tolkachev** [benji300/joplin-note-tabs#7]
This would be useful for quickly changing the active tab using the keyboard.

Possible commands:
- Switch to Left Tab
- Switch to Right Tab
- Switch to Previous Active Tab

**Comment by benji300** [comment]
Thanks for this proposal. But it is already implemented in the master branch with feature #5.
Only the third command is currently not available. Is it that much important?

**Comment by danil-tolkachev** [comment]
Not sure, but working with two tabs is a common case. Using one shortcut for switching between them is more convenient.
